# Site
name: "Jack High Bowls"
title: "Jack High Bowls indoor and lawn bowls"
description: "Bringing the best reviews and guides for indoor and lawn bowls"
meta_description: "Bringing the best reviews and guides for indoor and lawn bowls"
logo: ''
favicon: "/assets/images/favicon.ico"
baseurl: "https://www.jackhighbowls.com"
permalink: /:categories/:title
email: "contact@jackhighbowls.com"
google_analytics: "UA-86474387-5"

# Authors
authors:
  reece:
    name: Reece
    display_name: Reece
    gravatar:
    email: "contact@jackhighbowls.com"
    description: "Bringing the best reviews and guides for indoor and lawn bowls."
