# Site
name: "Jack High Bowls"
title: "Jack High Bowls indoor and lawn bowls"
description: "Bringing the best reviews and guides for indoor and lawn bowls"
meta_description: "Bringing the best reviews and guides for indoor and lawn bowls"
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: ''
permalink: /:categories/:title
email: 'wowthemesnet@gmail.com'
google_analytics: ''

# Authors
authors:
  reece:
    name: Reece
    display_name: Reece
    gravatar: ''
    email: wowthemesnet@gmail.com
    description: "Bringing the best reviews and guides for indoor and lawn bowls."
