# Site
name: "Etsy Simplicity"
title: "Helping Etsy sellers to grow their business"
description: "Helping Etsy sellers to grow their business"
meta_description: "Helping Etsy sellers to grow their business"
logo: ''
favicon: "/assets/images/favicon.ico"
baseurl: "https://www.etsysimplicity.com"
permalink: /:title
email: "reece@etsysimplicity.com"

# Authors
authors:
  reece:
    name: Reece
    display_name: Reece Williams
    gravatar:
    email: "reece@etsysimplicity.com"
    description: ""
