# Site
name: "Etsy Simplicity"
title: ""
description: ""
meta_description: ""
logo: ''
favicon: "/assets/images/favicon.ico"
baseurl: "https://www.etsysimplicity.com"
permalink: /:title
email: "reece@etsysimplicity.com"
google_analytics: "UA-86474387-5"

# Authors
authors:
  reece:
    name: Reece
    display_name: Reece Williams
    gravatar:
    email: "reece@etsysimplicity.com"
    description: ""
